



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//     Author: TECH SOLUTIONS PERU EIRL
//     Developer: Ronald Ibarra
//     Generated at: 06/16/2025 09:06:15
//     All Right reserved
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Linq;

namespace Tsp.Sigescom.Config
{



/// <summary>
///  Grupo de Investigación
/// </summary>
public sealed class LocalResearchGroupSettings
{
IDictionary<string, string> parametrosConfiguracion = new Dictionary<string, string>();




public LocalResearchGroupSettings(string TenantConnectionString)
        {
SqlConnection conn = new SqlConnection(TenantConnectionString);
//List<object> parametrosConfiguracion = new List<object>().Select(t => new { Id = default(int), Nombre = default(string), Valor=default(string) , Tipo=default(string), Descripcion=default(string)}).ToList(); 
string configuracionQuery = string.Format("select {0}, {1},{2},{3},{4} from {5} where businessSettingId={6} order by {0}", "id", "name", "value","description","dataType","BusinessSettingParameter",1);
SqlCommand parametroConfiguracionCommand = new SqlCommand(configuracionQuery, conn);
conn.Open();
        SqlDataReader parametroConfiguracionReader = parametroConfiguracionCommand.ExecuteReader();
        bool parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        while(parametroConfiguracionLoop)
        {

            parametrosConfiguracion.Add(parametroConfiguracionReader["name"].ToString(),parametroConfiguracionReader["value"].ToString()); 
            parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        }
conn.Close();





        }






        /// <summary>
        ///  Grupo de Investigación
        /// </summary>
        public int ResearchGroupId {
            get {
                                 return Convert.ToInt32(parametrosConfiguracion["ResearchGroupId"]);
               
            }
        }
    

}



/// <summary>
///  Área de Investigación
/// </summary>
public sealed class LocalResearchAreaSettings
{
IDictionary<string, string> parametrosConfiguracion = new Dictionary<string, string>();




public LocalResearchAreaSettings(string TenantConnectionString)
        {
SqlConnection conn = new SqlConnection(TenantConnectionString);
//List<object> parametrosConfiguracion = new List<object>().Select(t => new { Id = default(int), Nombre = default(string), Valor=default(string) , Tipo=default(string), Descripcion=default(string)}).ToList(); 
string configuracionQuery = string.Format("select {0}, {1},{2},{3},{4} from {5} where businessSettingId={6} order by {0}", "id", "name", "value","description","dataType","BusinessSettingParameter",2);
SqlCommand parametroConfiguracionCommand = new SqlCommand(configuracionQuery, conn);
conn.Open();
        SqlDataReader parametroConfiguracionReader = parametroConfiguracionCommand.ExecuteReader();
        bool parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        while(parametroConfiguracionLoop)
        {

            parametrosConfiguracion.Add(parametroConfiguracionReader["name"].ToString(),parametroConfiguracionReader["value"].ToString()); 
            parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        }
conn.Close();





        }






        /// <summary>
        ///  Área de Investigación
        /// </summary>
        public int ResearchAreaId {
            get {
                                 return Convert.ToInt32(parametrosConfiguracion["ResearchAreaId"]);
               
            }
        }
    

}



/// <summary>
///  Línea de Investigación
/// </summary>
public sealed class LocalResearchLineSettings
{
IDictionary<string, string> parametrosConfiguracion = new Dictionary<string, string>();




public LocalResearchLineSettings(string TenantConnectionString)
        {
SqlConnection conn = new SqlConnection(TenantConnectionString);
//List<object> parametrosConfiguracion = new List<object>().Select(t => new { Id = default(int), Nombre = default(string), Valor=default(string) , Tipo=default(string), Descripcion=default(string)}).ToList(); 
string configuracionQuery = string.Format("select {0}, {1},{2},{3},{4} from {5} where businessSettingId={6} order by {0}", "id", "name", "value","description","dataType","BusinessSettingParameter",3);
SqlCommand parametroConfiguracionCommand = new SqlCommand(configuracionQuery, conn);
conn.Open();
        SqlDataReader parametroConfiguracionReader = parametroConfiguracionCommand.ExecuteReader();
        bool parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        while(parametroConfiguracionLoop)
        {

            parametrosConfiguracion.Add(parametroConfiguracionReader["name"].ToString(),parametroConfiguracionReader["value"].ToString()); 
            parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        }
conn.Close();





        }






        /// <summary>
        ///  Línea de Investigación
        /// </summary>
        public int ResearchLineId {
            get {
                                 return Convert.ToInt32(parametrosConfiguracion["ResearchLineId"]);
               
            }
        }
    

}



/// <summary>
///  Docente Investigador
/// </summary>
public sealed class LocalDocenteSettings
{
IDictionary<string, string> parametrosConfiguracion = new Dictionary<string, string>();




public LocalDocenteSettings(string TenantConnectionString)
        {
SqlConnection conn = new SqlConnection(TenantConnectionString);
//List<object> parametrosConfiguracion = new List<object>().Select(t => new { Id = default(int), Nombre = default(string), Valor=default(string) , Tipo=default(string), Descripcion=default(string)}).ToList(); 
string configuracionQuery = string.Format("select {0}, {1},{2},{3},{4} from {5} where businessSettingId={6} order by {0}", "id", "name", "value","description","dataType","BusinessSettingParameter",4);
SqlCommand parametroConfiguracionCommand = new SqlCommand(configuracionQuery, conn);
conn.Open();
        SqlDataReader parametroConfiguracionReader = parametroConfiguracionCommand.ExecuteReader();
        bool parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        while(parametroConfiguracionLoop)
        {

            parametrosConfiguracion.Add(parametroConfiguracionReader["name"].ToString(),parametroConfiguracionReader["value"].ToString()); 
            parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        }
conn.Close();





        }






        /// <summary>
        ///  Docente
        /// </summary>
        public int DocenteId {
            get {
                                 return Convert.ToInt32(parametrosConfiguracion["DocenteId"]);
               
            }
        }
    

}



/// <summary>
///  Proyecto de Investigación
/// </summary>
public sealed class LocalProjectSettings
{
IDictionary<string, string> parametrosConfiguracion = new Dictionary<string, string>();




public LocalProjectSettings(string TenantConnectionString)
        {
SqlConnection conn = new SqlConnection(TenantConnectionString);
//List<object> parametrosConfiguracion = new List<object>().Select(t => new { Id = default(int), Nombre = default(string), Valor=default(string) , Tipo=default(string), Descripcion=default(string)}).ToList(); 
string configuracionQuery = string.Format("select {0}, {1},{2},{3},{4} from {5} where businessSettingId={6} order by {0}", "id", "name", "value","description","dataType","BusinessSettingParameter",5);
SqlCommand parametroConfiguracionCommand = new SqlCommand(configuracionQuery, conn);
conn.Open();
        SqlDataReader parametroConfiguracionReader = parametroConfiguracionCommand.ExecuteReader();
        bool parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        while(parametroConfiguracionLoop)
        {

            parametrosConfiguracion.Add(parametroConfiguracionReader["name"].ToString(),parametroConfiguracionReader["value"].ToString()); 
            parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        }
conn.Close();





        }






        /// <summary>
        ///  Proyecto de Investigación
        /// </summary>
        public int ProjectId {
            get {
                                 return Convert.ToInt32(parametrosConfiguracion["ProjectId"]);
               
            }
        }
    

}



/// <summary>
///  Tipo de Documento
/// </summary>
public sealed class LocalDocumentTypeSettings
{
IDictionary<string, string> parametrosConfiguracion = new Dictionary<string, string>();




public LocalDocumentTypeSettings(string TenantConnectionString)
        {
SqlConnection conn = new SqlConnection(TenantConnectionString);
//List<object> parametrosConfiguracion = new List<object>().Select(t => new { Id = default(int), Nombre = default(string), Valor=default(string) , Tipo=default(string), Descripcion=default(string)}).ToList(); 
string configuracionQuery = string.Format("select {0}, {1},{2},{3},{4} from {5} where businessSettingId={6} order by {0}", "id", "name", "value","description","dataType","BusinessSettingParameter",6);
SqlCommand parametroConfiguracionCommand = new SqlCommand(configuracionQuery, conn);
conn.Open();
        SqlDataReader parametroConfiguracionReader = parametroConfiguracionCommand.ExecuteReader();
        bool parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        while(parametroConfiguracionLoop)
        {

            parametrosConfiguracion.Add(parametroConfiguracionReader["name"].ToString(),parametroConfiguracionReader["value"].ToString()); 
            parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        }
conn.Close();





        }






        /// <summary>
        ///  Tipo de Documento
        /// </summary>
        public int DocumentTypeId {
            get {
                                 return Convert.ToInt32(parametrosConfiguracion["DocumentTypeId"]);
               
            }
        }
    

}



/// <summary>
///  Estado del Tipo de Proyecto
/// </summary>
public sealed class LocalStateProjectTypeSettings
{
IDictionary<string, string> parametrosConfiguracion = new Dictionary<string, string>();




public LocalStateProjectTypeSettings(string TenantConnectionString)
        {
SqlConnection conn = new SqlConnection(TenantConnectionString);
//List<object> parametrosConfiguracion = new List<object>().Select(t => new { Id = default(int), Nombre = default(string), Valor=default(string) , Tipo=default(string), Descripcion=default(string)}).ToList(); 
string configuracionQuery = string.Format("select {0}, {1},{2},{3},{4} from {5} where businessSettingId={6} order by {0}", "id", "name", "value","description","dataType","BusinessSettingParameter",7);
SqlCommand parametroConfiguracionCommand = new SqlCommand(configuracionQuery, conn);
conn.Open();
        SqlDataReader parametroConfiguracionReader = parametroConfiguracionCommand.ExecuteReader();
        bool parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        while(parametroConfiguracionLoop)
        {

            parametrosConfiguracion.Add(parametroConfiguracionReader["name"].ToString(),parametroConfiguracionReader["value"].ToString()); 
            parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        }
conn.Close();





        }






        /// <summary>
        ///  Estado del Tipo de Proyecto
        /// </summary>
        public int StateProjectTypeId {
            get {
                                 return Convert.ToInt32(parametrosConfiguracion["StateProjectTypeId"]);
               
            }
        }
    

}



/// <summary>
///  Actor del Proyecto
/// </summary>
public sealed class LocalActorProjectSettings
{
IDictionary<string, string> parametrosConfiguracion = new Dictionary<string, string>();




public LocalActorProjectSettings(string TenantConnectionString)
        {
SqlConnection conn = new SqlConnection(TenantConnectionString);
//List<object> parametrosConfiguracion = new List<object>().Select(t => new { Id = default(int), Nombre = default(string), Valor=default(string) , Tipo=default(string), Descripcion=default(string)}).ToList(); 
string configuracionQuery = string.Format("select {0}, {1},{2},{3},{4} from {5} where businessSettingId={6} order by {0}", "id", "name", "value","description","dataType","BusinessSettingParameter",8);
SqlCommand parametroConfiguracionCommand = new SqlCommand(configuracionQuery, conn);
conn.Open();
        SqlDataReader parametroConfiguracionReader = parametroConfiguracionCommand.ExecuteReader();
        bool parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        while(parametroConfiguracionLoop)
        {

            parametrosConfiguracion.Add(parametroConfiguracionReader["name"].ToString(),parametroConfiguracionReader["value"].ToString()); 
            parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        }
conn.Close();





        }






        /// <summary>
        ///  Actor del Proyecto
        /// </summary>
        public int ActorProjectId {
            get {
                                 return Convert.ToInt32(parametrosConfiguracion["ActorProjectId"]);
               
            }
        }
    

}



/// <summary>
///  Fondos
/// </summary>
public sealed class LocalFundingSettings
{
IDictionary<string, string> parametrosConfiguracion = new Dictionary<string, string>();




public LocalFundingSettings(string TenantConnectionString)
        {
SqlConnection conn = new SqlConnection(TenantConnectionString);
//List<object> parametrosConfiguracion = new List<object>().Select(t => new { Id = default(int), Nombre = default(string), Valor=default(string) , Tipo=default(string), Descripcion=default(string)}).ToList(); 
string configuracionQuery = string.Format("select {0}, {1},{2},{3},{4} from {5} where businessSettingId={6} order by {0}", "id", "name", "value","description","dataType","BusinessSettingParameter",9);
SqlCommand parametroConfiguracionCommand = new SqlCommand(configuracionQuery, conn);
conn.Open();
        SqlDataReader parametroConfiguracionReader = parametroConfiguracionCommand.ExecuteReader();
        bool parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        while(parametroConfiguracionLoop)
        {

            parametrosConfiguracion.Add(parametroConfiguracionReader["name"].ToString(),parametroConfiguracionReader["value"].ToString()); 
            parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        }
conn.Close();





        }






        /// <summary>
        ///  Fondos
        /// </summary>
        public int FundingId {
            get {
                                 return Convert.ToInt32(parametrosConfiguracion["FundingId"]);
               
            }
        }
    

}



/// <summary>
///  Métodos para un Proyecto
/// </summary>
public sealed class LocalMethodProjectTypeSettings
{
IDictionary<string, string> parametrosConfiguracion = new Dictionary<string, string>();




public LocalMethodProjectTypeSettings(string TenantConnectionString)
        {
SqlConnection conn = new SqlConnection(TenantConnectionString);
//List<object> parametrosConfiguracion = new List<object>().Select(t => new { Id = default(int), Nombre = default(string), Valor=default(string) , Tipo=default(string), Descripcion=default(string)}).ToList(); 
string configuracionQuery = string.Format("select {0}, {1},{2},{3},{4} from {5} where businessSettingId={6} order by {0}", "id", "name", "value","description","dataType","BusinessSettingParameter",10);
SqlCommand parametroConfiguracionCommand = new SqlCommand(configuracionQuery, conn);
conn.Open();
        SqlDataReader parametroConfiguracionReader = parametroConfiguracionCommand.ExecuteReader();
        bool parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        while(parametroConfiguracionLoop)
        {

            parametrosConfiguracion.Add(parametroConfiguracionReader["name"].ToString(),parametroConfiguracionReader["value"].ToString()); 
            parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        }
conn.Close();





        }






        /// <summary>
        ///  Métodos para un Proyecto
        /// </summary>
        public int MethodProjectTypeId {
            get {
                                 return Convert.ToInt32(parametrosConfiguracion["MethodProjectTypeId"]);
               
            }
        }
    

}



/// <summary>
///  Objetivos de Desarrollo Sostenible
/// </summary>
public sealed class LocalODSObjectiveSettings
{
IDictionary<string, string> parametrosConfiguracion = new Dictionary<string, string>();




public LocalODSObjectiveSettings(string TenantConnectionString)
        {
SqlConnection conn = new SqlConnection(TenantConnectionString);
//List<object> parametrosConfiguracion = new List<object>().Select(t => new { Id = default(int), Nombre = default(string), Valor=default(string) , Tipo=default(string), Descripcion=default(string)}).ToList(); 
string configuracionQuery = string.Format("select {0}, {1},{2},{3},{4} from {5} where businessSettingId={6} order by {0}", "id", "name", "value","description","dataType","BusinessSettingParameter",11);
SqlCommand parametroConfiguracionCommand = new SqlCommand(configuracionQuery, conn);
conn.Open();
        SqlDataReader parametroConfiguracionReader = parametroConfiguracionCommand.ExecuteReader();
        bool parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        while(parametroConfiguracionLoop)
        {

            parametrosConfiguracion.Add(parametroConfiguracionReader["name"].ToString(),parametroConfiguracionReader["value"].ToString()); 
            parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        }
conn.Close();





        }






        /// <summary>
        ///  Objetivos de Desarrollo Sostenible
        /// </summary>
        public int ODSObjectiveId {
            get {
                                 return Convert.ToInt32(parametrosConfiguracion["ODSObjectiveId"]);
               
            }
        }
    

}



/// <summary>
///  Solicitudes de prácticas preprofesionales
/// </summary>
public sealed class LocalRequestPPPSettings
{
IDictionary<string, string> parametrosConfiguracion = new Dictionary<string, string>();




public LocalRequestPPPSettings(string TenantConnectionString)
        {
SqlConnection conn = new SqlConnection(TenantConnectionString);
//List<object> parametrosConfiguracion = new List<object>().Select(t => new { Id = default(int), Nombre = default(string), Valor=default(string) , Tipo=default(string), Descripcion=default(string)}).ToList(); 
string configuracionQuery = string.Format("select {0}, {1},{2},{3},{4} from {5} where businessSettingId={6} order by {0}", "id", "name", "value","description","dataType","BusinessSettingParameter",12);
SqlCommand parametroConfiguracionCommand = new SqlCommand(configuracionQuery, conn);
conn.Open();
        SqlDataReader parametroConfiguracionReader = parametroConfiguracionCommand.ExecuteReader();
        bool parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        while(parametroConfiguracionLoop)
        {

            parametrosConfiguracion.Add(parametroConfiguracionReader["name"].ToString(),parametroConfiguracionReader["value"].ToString()); 
            parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        }
conn.Close();





        }






        /// <summary>
        ///  Estado de RequestPPP
        /// </summary>
        public int StateRequestPPPId {
            get {
                                 return Convert.ToInt32(parametrosConfiguracion["StateRequestPPPId"]);
               
            }
        }
    

}



/// <summary>
///  Prácticas preprofesionales
/// </summary>
public sealed class LocalPreProfessionalInternshipSettings
{
IDictionary<string, string> parametrosConfiguracion = new Dictionary<string, string>();




public LocalPreProfessionalInternshipSettings(string TenantConnectionString)
        {
SqlConnection conn = new SqlConnection(TenantConnectionString);
//List<object> parametrosConfiguracion = new List<object>().Select(t => new { Id = default(int), Nombre = default(string), Valor=default(string) , Tipo=default(string), Descripcion=default(string)}).ToList(); 
string configuracionQuery = string.Format("select {0}, {1},{2},{3},{4} from {5} where businessSettingId={6} order by {0}", "id", "name", "value","description","dataType","BusinessSettingParameter",13);
SqlCommand parametroConfiguracionCommand = new SqlCommand(configuracionQuery, conn);
conn.Open();
        SqlDataReader parametroConfiguracionReader = parametroConfiguracionCommand.ExecuteReader();
        bool parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        while(parametroConfiguracionLoop)
        {

            parametrosConfiguracion.Add(parametroConfiguracionReader["name"].ToString(),parametroConfiguracionReader["value"].ToString()); 
            parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        }
conn.Close();





        }






    

}



/// <summary>
///  Ofertas laborales relacionadas con empresas
/// </summary>
public sealed class LocalJobOfferSettings
{
IDictionary<string, string> parametrosConfiguracion = new Dictionary<string, string>();




public LocalJobOfferSettings(string TenantConnectionString)
        {
SqlConnection conn = new SqlConnection(TenantConnectionString);
//List<object> parametrosConfiguracion = new List<object>().Select(t => new { Id = default(int), Nombre = default(string), Valor=default(string) , Tipo=default(string), Descripcion=default(string)}).ToList(); 
string configuracionQuery = string.Format("select {0}, {1},{2},{3},{4} from {5} where businessSettingId={6} order by {0}", "id", "name", "value","description","dataType","BusinessSettingParameter",14);
SqlCommand parametroConfiguracionCommand = new SqlCommand(configuracionQuery, conn);
conn.Open();
        SqlDataReader parametroConfiguracionReader = parametroConfiguracionCommand.ExecuteReader();
        bool parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        while(parametroConfiguracionLoop)
        {

            parametrosConfiguracion.Add(parametroConfiguracionReader["name"].ToString(),parametroConfiguracionReader["value"].ToString()); 
            parametroConfiguracionLoop = parametroConfiguracionReader.Read();
        }
conn.Close();





        }






    

}


public partial class SettingsContainer
    {

                      public  LocalResearchGroupSettings LocalResearchGroupSettings;

                   public  LocalResearchAreaSettings LocalResearchAreaSettings;

                   public  LocalResearchLineSettings LocalResearchLineSettings;

                   public  LocalDocenteSettings LocalDocenteSettings;

                   public  LocalProjectSettings LocalProjectSettings;

                   public  LocalDocumentTypeSettings LocalDocumentTypeSettings;

                   public  LocalStateProjectTypeSettings LocalStateProjectTypeSettings;

                   public  LocalActorProjectSettings LocalActorProjectSettings;

                   public  LocalFundingSettings LocalFundingSettings;

                   public  LocalMethodProjectTypeSettings LocalMethodProjectTypeSettings;

                   public  LocalODSObjectiveSettings LocalODSObjectiveSettings;

                   public  LocalRequestPPPSettings LocalRequestPPPSettings;

                   public  LocalPreProfessionalInternshipSettings LocalPreProfessionalInternshipSettings;

                   public  LocalJobOfferSettings LocalJobOfferSettings;

                 

        public SettingsContainer(string tenantConnectionString)
        {
                            LocalResearchGroupSettings = new  LocalResearchGroupSettings(tenantConnectionString);

                   LocalResearchAreaSettings = new  LocalResearchAreaSettings(tenantConnectionString);

                   LocalResearchLineSettings = new  LocalResearchLineSettings(tenantConnectionString);

                   LocalDocenteSettings = new  LocalDocenteSettings(tenantConnectionString);

                   LocalProjectSettings = new  LocalProjectSettings(tenantConnectionString);

                   LocalDocumentTypeSettings = new  LocalDocumentTypeSettings(tenantConnectionString);

                   LocalStateProjectTypeSettings = new  LocalStateProjectTypeSettings(tenantConnectionString);

                   LocalActorProjectSettings = new  LocalActorProjectSettings(tenantConnectionString);

                   LocalFundingSettings = new  LocalFundingSettings(tenantConnectionString);

                   LocalMethodProjectTypeSettings = new  LocalMethodProjectTypeSettings(tenantConnectionString);

                   LocalODSObjectiveSettings = new  LocalODSObjectiveSettings(tenantConnectionString);

                   LocalRequestPPPSettings = new  LocalRequestPPPSettings(tenantConnectionString);

                   LocalPreProfessionalInternshipSettings = new  LocalPreProfessionalInternshipSettings(tenantConnectionString);

                   LocalJobOfferSettings = new  LocalJobOfferSettings(tenantConnectionString);

     
        SetDictionaries();
        }
   }
}